### ISSUE TITLE
Q: Making the test story terser

### ISSUE THREAD

**Issue by runspired** [customerio/ember-provide-consume-context#18]
Currently, if you wanted to migrate from services to contexts, or if you wanted to set up contexts associated with routes or your app overall, then integration tests would need to provide their own copy of each context. That looks a bit like this:

```js
await render(
  hbs`<ContextProvider @key="store" @value={{this.store}}>
    {{! ... test code here...}}
  </ContextProvider>`
);
```

Both for providing support for migrations, and for just general test terseness, it would be awesome if for instance in a `beforeEach` a context could be provided for use in the associated tests.

E.g.

```ts
import { module, test } from 'qunit';
import { setupRenderingTest } from 'ember-qunit';
import { render } from '@ember/test-helpers';
import { hbs } from 'ember-cli-htmlbars';
import Store from 'ember-data/store';
import { provide } from 'ember-provide-consume-context/test-support';

module('some tests', function(hooks) {
  setupRenderingTest(hooks);
  
  hooks.beforeEach(function() {
    const store = new Store();
    store.push({
      data: { type: 'user', id: '1', attributes: { name: 'Chris' } }
    });
  
    provide(this, 'store', store);
  });
  
  test('it renders!', async function(assert) {
    await render(hbs`<UserPreview @userId={{"1"}} />`);
    
    assert.dom('h1').hasText('Chris');
  });
});
```

**Comment by kevinkucharczyk** [comment]
@runspired thanks for another excellent suggestion! I'll be adding two test helpers via https://github.com/customerio/ember-provide-consume-context/pull/20
