### ISSUE TITLE
Cannot find module 'ember-provide-consume-context/test-support' 

### ISSUE THREAD

**Issue by jurgenwerk** [customerio/ember-provide-consume-context#24]
Hi, thanks for making this addon. I am trying to use test support helpers but getting the mentioned TypeScript error when importing: `import { provide } from 'ember-provide-consume-context/test-support';`

**Comment by kevinkucharczyk** [comment]
@jurgenwerk hi again! I'm shipping a fix for your issue under version 0.3.2 (via https://github.com/customerio/ember-provide-consume-context/pull/25). Turns out the `package.json` entries weren't quite correct. Please let me know if you have any other issues!

**Comment by jurgenwerk** [comment]
@kevinkucharczyk Awesome! Thank you.
